<?php

namespace App\Controller;

use App\Entity\FtpServer;
use App\Service\FtpManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AssistRulesController extends AbstractJsonFileFormController
{
    /**
     * @Route("/dashboard/file/{id<\d+>}/assist/rules", name="assist_rules")
     *
     * @inheritDoc
     */
    public function edit(FtpServer $ftpServer, FtpManager $ftpManager, Request $request): Response
    {
        return parent::edit($ftpServer, $ftpManager, $request); // @TODO: Change the autogenerated stub
    }
}
